name: Sync submodule commit to parent

on:
  push:
    branches: [main]

jobs:
  sync-parent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório-filho (atual)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura Git
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@example.com"

      - name: Checkout repo-pai com submódulos
        uses: actions/checkout@v4
        with:
          repository: Lukas712/mono-repo-with-submodules
          token: ${{ secrets.GH_TOKEN }}
          path: mono-repo-with-submodules
          submodules: recursive
          fetch-depth: 0

      - name: Substitui conteúdo do submódulo pelo commit atual do repositório-filho
        run: |
          cd mono-repo-with-submodules

          # ⚠️ Substitua pelo caminho correto do submódulo dentro do repositório-pai
          SUBMODULE_PATH=submodule-one

          # Remove conteúdo antigo do submódulo
          rm -rf $SUBMODULE_PATH/*

          # Copia novo conteúdo (exceto .git e .github)
          rsync -av --exclude='.git' --exclude='.github' ../ $SUBMODULE_PATH/

          git add $SUBMODULE_PATH
          git diff --cached --quiet || (git commit -m "Sync submódulo com commit atual do repositório-filho" && git push)
