on:
  push:
    branches: [main]

jobs:
  sync-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout filho
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura Git
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@example.com"

      - name: Checkout repo-pai c/ submódulos
        uses: actions/checkout@v4
        with:
          repository: Lukas712/mono-repo-with-submodules
          token: ${{ secrets.GH_TOKEN }}
          path: mono-repo-with-submodules
          submodules: recursive
          fetch-depth: 0

      - name: Espera 5 segundos para garantir visibilidade do commit
        run: sleep 5

      - name: Captura a mensagem do último commit
        run: |
          # Captura a mensagem do último commit no repositório atual
          commit_message=$(git log -1 --pretty=%B)

      - name: Atualiza todos submódulos pra branch principal
        run: |
          cd mono-repo-with-submodules
          git config user.name "GitHub Bot"
          git config user.email "bot@example.com"

          # Atualiza os submódulos
          git submodule update --remote --merge

          # Faz o commit no repositório pai com a mensagem do commit do repositório atual
          git add .
          git diff --cached --quiet || ( git commit -m "$commit_message" && git push )
