name: Sync submodule commit to parent

on:
  push:
    branches: [main]

jobs:
  sync-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout filho
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura Git
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@example.com"

      - name: Clone repo-pai
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Lukas712/mono-repo-with-submodules.git repo-pai
          cd repo-pai

          # Inicializa e baixa o conteúdo dos submódulos
          git submodule init
          git submodule update --recursive

          # Agora a pasta microservico-a/ existe e podemos atualizar:
          git submodule update --remote --merge microservico-a

          git add microservico-a
          if ! git diff --cached --quiet; then
            git config user.name "GitHub Bot"
            git config user.email "bot@example.com"
            git commit -m "Atualização do submódulo microservico-a: ${{ github.sha }}"
            git push origin main
          fi

