on:
  push:
    branches: [main]

jobs:
  sync-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout filho
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante que o histórico completo de commits é obtido

      - name: Configura Git
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@example.com"

      - name: Captura a mensagem do último commit no repositório filho
        run: |
          commit_message=$(git log -1 --pretty=%B)
          repo_name="${GITHUB_REPOSITORY}"
          commit_message_with_repo="${commit_message} [Commit do repositório ${repo_name}]"
          echo "commit_message_with_repo=$commit_message_with_repo" >> $GITHUB_ENV

      - name: Checkout repo-pai c/ submódulos
        uses: actions/checkout@v4
        with:
          repository: Lukas712/mono-repo-with-submodules
          token: ${{ secrets.GH_TOKEN }}
          path: mono-repo-with-submodules
          submodules: recursive
          fetch-depth: 0

      - name: Espera 5 segundos para garantir visibilidade do commit
        run: sleep 5

      - name: Atualiza todos submódulos pra branch principal
        run: |
          cd mono-repo-with-submodules
          git config user.name "GitHub Bot"
          git config user.email "bot@example.com"

          git submodule update --remote --merge

          git add .
          git diff --cached --quiet || ( git commit -m "$commit_message_with_repo" && git push )
